### ISSUE TITLE
Documentation mixedPenalty function

### ISSUE THREAD

**Issue by B260198** [jhorzek/lessSEM#355]
Dear Jannik,

I  had a bit of trouble understanding the functionality of each argument of the mixedPenalty function. When typing ?mixedPenalty in the console you get a different documentation than [here](https://cran.r-project.org/web/packages/lessSEM/vignettes/Mixed-Penalties.html). I found the documentation in the console a bit confusing, especially if you haven't worked with lessSEM much. Maybe you can add a little more to it?

Best, 
Britta

**Comment by jhorzek** [comment]
Good point! I'll update the documentation :).

**Comment by jhorzek** [comment]
I'll leave the issue open as a reminder to myself to adapt the documentation. Once that is done, I'll close it again :)
